spring:
  profile: dev
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:8081/TRANSACOES?currentSchema=DBCOMPRA
    driver-class-name: org.postgresql.Driver
    username: csv-batch
    password: csv-batch
  batch:
    initialize-schema: always

file:
  reader:
    key: fileReader
  name:
    key: fileName
  line:
    key: fileLine
  column:
    line: 1