version: '3'
services:
  db:
    container_name: db-postgresql
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: csv-batch
      POSTGRES_USER: csv-batch
      POSTGRES_DB: TRANSACOES
    ports:
      - '8081:5432'